### ISSUE TITLE
可以支持notion吗

### ISSUE THREAD

**Issue by MichaelHugh** [piglei/ai-vocabulary-builder#13]
我平时把生词都是记录在notion里面

**Comment by piglei** [comment]
可以支持导出功能，方便的话截个图吧。我看看你的生词表做的是啥样的😁

**Comment by MichaelHugh** [comment]
> 可以支持导出功能，方便的话截个图吧。我看看你的生词表做的是啥样的😁

我的比较简单，只有单词，释义以及例句，然后加上一个多选的property标签，分为新词，半生不熟词，死活记不住的词，再加上一个创建时间，可以通过时间来排序以及确定什么时候复习

**Comment by piglei** [comment]
试了下 Notion 支持导入 CSV 格式的文件。你可以更新生词本工具到最新版，然后用 `aivoc export --format csv` 来导出 CSV 文件，再导入到 Notion 试试。
