### ISSUE TITLE
考虑增加 GUI 模式

### ISSUE THREAD

**Issue by piglei** [piglei/ai-vocabulary-builder#15]
综合权衡，感觉未来需要做一个 GUI 模式。优点：

- 上手门槛更低，许多操作用 REPL 模式并不算直观
- 和划词插件整合后，有一个 GUI 可以方便用户更便捷的操作最近添加的生词

**Comment by haydenull** [comment]
大佬有啥想法吗，我最近也有这个需求，周末糊了个简单的 MVP，但是没有后端经验，有点拉

这个是 demo 地址 https://encounter.haydenhayden.com/
这个是仓库 https://github.com/haydenull/encounter-mem

**Comment by piglei** [comment]
> 大佬有啥想法吗，我最近也有这个需求，周末糊了个简单的 MVP，但是没有后端经验，有点拉
> 
> 这个是 demo 地址 https://encounter.haydenhayden.com/ 这个是仓库 https://github.com/haydenull/encounter-mem

简单用了下，感觉还可以呀。不过你的思路和我当前想的不太一样，我目前对于“AI 生词本” GUI 分支的一些想法：

- 在共享已有的底层代码的基础上，实现 Server 模式，对外表现为执行 `aivoc notebook` 命令，打开浏览器 Tab（类似于 jupter notebook），用户可以翻译、查看故事模式以及查看和管理生词本
- 保留已有的通过 CLI 方式使用工具的能力，比如 REPL、export 等，和 Web 模式共享数据
- Server 端通过 REST API，与其他本地划词翻译插件（OpenAI Translator、Bob 插件）进行适配和集成
- 未来，如果有必要的话，用打包工具将软件包装为 Native App 分发到各平台
- 总是还是优先适配在本地安装和使用，当然也有以作为 SaaS 部署的能力

如果你对这个思路感兴趣的话，可以邮件我，我们详聊看看是不是能够一起搞。

**Comment by haydenull** [comment]
确实咱们的思路不太一样，我是根据自己的使用场景设计的。我的整块阅读时间基本都是耗费在移动端，所以网页或者 APP 是我考虑的第一入口。包括复习单词也都是在移动端进行，pc 端主要是收集生词。最终是想做一个背单词软件的补充。

如果你的项目以后需要开发 web 端的话我很乐意参与。💖

**Comment by piglei** [comment]
已经在 0.6.0 版本实现。

**Comment by piglei** [comment]
关闭。目前 v1.2 版本已经实现大部分之前设想的 GUI 能力。
