### ISSUE TITLE
下载时提示不能找到对应版本

### ISSUE THREAD

**Issue by mrobotf** [piglei/ai-vocabulary-builder#18]
pip install ai-vocabulary-builder 命令始终无法正确运行
我尝试过换源，如下图
![image](https://user-images.githubusercontent.com/93702449/223462877-016cfe75-8cf1-47b4-b25e-a454f4fc4903.png)
![image](https://user-images.githubusercontent.com/93702449/223462936-7b32c048-ece8-4175-89a7-0ebbd2a82994.png)

我使用的python版本是 3.7：
![image](https://user-images.githubusercontent.com/93702449/223463461-c957024c-13e3-4334-8670-ebfb4bce7049.png)

希望能得到解答，谢谢

**Comment by Fit-yourself** [comment]
試著把 base 環境版本升級到 Python 3.7.1

**Comment by piglei** [comment]
> pip install ai-vocabulary-builder 命令始终无法正确运行 我尝试过换源，如下图 ![image](https://user-images.githubusercontent.com/93702449/223462877-016cfe75-8cf1-47b4-b25e-a454f4fc4903.png) ![image](https://user-images.githubusercontent.com/93702449/223462936-7b32c048-ece8-4175-89a7-0ebbd2a82994.png)
> 
> 我使用的python版本是 3.7： ![image](https://user-images.githubusercontent.com/93702449/223463461-c957024c-13e3-4334-8670-ebfb4bce7049.png)
> 
> 希望能得到解答，谢谢

指定一下使用官方的 PyPI 源地址吧，国内的镜像同步需要一些时间。

> pip install --index-url=https://pypi.org/simple/ ai-vocabulary-builder
