### ISSUE TITLE
生詞提取存在問題，能否提供手動單詞選擇 option

### ISSUE THREAD

**Issue by Fit-yourself** [piglei/ai-vocabulary-builder#19]
### 情況
![图片](https://user-images.githubusercontent.com/45476879/223606824-701844cd-97c3-4ca6-93c7-935ce4f544e5.png)

儅生詞提取為中文時，無法添加單詞至單詞本。

---
- [  ] 那能否提供直接選擇 word 的參數？ 因爲有些時候 response 太慢了，切換模式還不如我先行選擇。 😢

有時請求時間有點緩慢，如果能提供這個選項，是否會改進導入效果？
難道在  #15 的 GUI 中可以實現嗎？

我之前使用過 [obsidian-language-learner](https://github.com/guopenghui/obsidian-language-learner)，它利用了 `i+1` 等假説理論進行大量閲讀，類似於一款應用 [LingQ](https://www.lingq.com)， **Immersion Reading**。

### 系統
- Windows 11
- Python 3.10.8

**Comment by piglei** [comment]
有道理的，但完全手动去选单词的话，也存在慢的问题，因为得请求服务端拿到这个词的释义。

不过我会先修复下你发的这个用例。就是当 ai 返回的词不对（不在原句子里）时，no 命令仍然可用，尝试自动提取 3 个单词出来。

**Comment by piglei** [comment]
已经在最新版中修复无法选择生词问题，请更新版本：

    pip install --upgrade --index-url=https://pypi.org/simple/ ai-vocabulary-builder
