### ISSUE TITLE
支持 Quiz（测试） 模式

### ISSUE THREAD

**Issue by piglei** [piglei/ai-vocabulary-builder#2]
- 支持使用 `aivoc quiz` 命令进入测试模式
- 用户选择本次测试的单词数量
- 通过展示例句，隐藏原单词的方式，测试对单词的掌握程度
- 最好做的有趣一点

**Comment by chuilishi** [comment]
为什么是aidoc?搞了半天,原来是打错字了..

**Comment by chuilishi** [comment]
没有看到功能哇,quiz没有用

**Comment by piglei** [comment]
> 没有看到功能哇,quiz没有用

你好，这个就是描述还没有实现的功能哦。

**Comment by piglei** [comment]
已经在 1.2 版本实现。
