### ISSUE TITLE
当一个句子中存在多个生词

### ISSUE THREAD

**Issue by wayne3602** [piglei/ai-vocabulary-builder#24]
如题，对于一个英语句子我有好几个生词不认识，但是它只给出了我一个可能不认识的单词，我只能选择no抛弃这个选择另一个，但是目前这个单词也是我不认识的，我不想抛弃他，我想添加多个

**Comment by piglei** [comment]
有一定道理，但我没想好直接把单选改成多选是否合理。主要在于，如果添加两个生词，但这俩词的例句完全相同的话，会比较奇怪。我再想想。

**Comment by wayne3602** [comment]
@piglei 这个问题很常见吧，经常会碰到一个句子有好几个生词，期待改进

**Comment by doublessay** [comment]
@piglei 我觉得这样问题不太大，关于交互逻辑，我觉得可以设置一个关键字 continue, 输入continue，给出其他可能的生词

**Comment by piglei** [comment]
已经在 0.5.0 版本中支持，可升级体验：

pip install --upgrade ai-vocabulary-builder
