### ISSUE TITLE
gbk编码问题

### ISSUE THREAD

**Issue by HeadmasterEggy** [piglei/ai-vocabulary-builder#25]
哥们太菜不知道怎么调编码...还请指点
![image](https://user-images.githubusercontent.com/93173363/224035109-eddc3899-56d9-4c15-a0ab-2c4f0e0a5f7b.png)

**Comment by piglei** [comment]
你用的这个版本比较老，请直接更新到新版解决：

    pip install --index-url=https://pypi.org/simple/ ai-vocabulary-builder
