### ISSUE TITLE
到处的csv中文是乱码

### ISSUE THREAD

**Issue by Caesar1980** [piglei/ai-vocabulary-builder#37]
按照步骤导出的csv中文现实乱码

**Comment by piglei** [comment]
`export` 命令所导出的 csv 文件使用了 UTF-8 编码。不知道你用的是什么编辑器，你可能需要调整编辑器设置来正常展示 UTF-8 编码。

**Comment by Love4yzp** [comment]
我猜测你应该是在 Windows 下用了  Excel 打开。 由于本程式的 csv 导出只是 UTF-8，而不是 UTF-8 with BOM，所以 Excel 读取时不会以 UTF-8 的编码方式读取，导致中文乱码。
> 引用：https://zhuanlan.zhihu.com/p/364136283
