### ISSUE TITLE
安装了python库之后运行命令没反应？

### ISSUE THREAD

**Issue by ithou** [piglei/ai-vocabulary-builder#38]
![CleanShot 2023-03-13 at 22 48 56@2x](https://user-images.githubusercontent.com/39048771/224737818-b6793bcb-1c55-4a02-8633-5635eaa412a7.png)

**Comment by piglei** [comment]
- 试着另外起一个新的 shell，然后执行 aivoc run 看看
- 请提供一下安装命令的完整输出

**Comment by ithou** [comment]
> * 试着另外起一个新的 shell，然后执行 aivoc run 看看
> * 请提供一下安装命令的完整输出

已经新开了iterm2运行了，这样可以吗？麻烦帮忙看看，谢谢🙏
- `Python 3.9` Mac M1 默认安装版本

![CleanShot 2023-03-14 at 19 45 46@2x](https://user-images.githubusercontent.com/39048771/224991536-8887f2d8-4efb-4c7c-8624-6ffa29f0441c.png)

**Comment by piglei** [comment]
感觉和你本身的 pip3 所使用的 Python 环境有关系，需要具体排查下，aivoc 命令应该是被安装到了一个不属于 $PATH 的地方。具体可以搜索下：pip after install executable not found 之类的关键词看看。

我搜到了一个资料：[python - Why aren't pip-installed executables available from the command line? - Super User](https://superuser.com/questions/1204232/why-arent-pip-installed-executables-available-from-the-command-line)
