### ISSUE TITLE
支持使用 Server 服务端模式启动

### ISSUE THREAD

**Issue by piglei** [piglei/ai-vocabulary-builder#4]
本工具如果需要和划词搜索等浏览器插件联动，必须通过 HTTP API 的方式对外提供服务。

- 增加 `aivoc server -d` 命令，支持在后台启动服务器
- 通过 HTTP API 提供翻译并添加生词接口（目前不支持重选）

**Comment by mobilestack** [comment]
bob有个问题是，收藏的有的是单词，更多的是对句子的翻译。所以收藏列表就会略显的乱。

现在我用自己包的popclip插件来使用aivoc，唯一的问题是需要我开着iterm，每次popclip选择一个句子后，需要在iterm中先激活venv环境，再去翻译。虽然也都在后台，不过不适合非技术受众。

其实现在的翻译的软件很多，各种软件都可以一行代码调用chatgpt来翻译，但是生词本管理上做的还不够，感觉可以就生词本这一个单点做更多优化。上游接受bob和欧路词典等翻译软件的数据导出，下游传递到划词复习的手机app，此外，可以做一下找AI编出的故事的持久化，或者让故事情节保持连续，形成有动力持续回顾的内容。

**Comment by piglei** [comment]
已经在 1.2 版本实现。

可以试试新版本 @mobilestack
