### ISSUE TITLE
可以增加查看生词列表的功能吗

### ISSUE THREAD

**Issue by doublessay** [piglei/ai-vocabulary-builder#40]
例如，查看所有的生词，最先添加的几个或者是最新添加的几个单词

**Comment by piglei** [comment]
使用 `aivoc export 命令可以查看`。 https://github.com/piglei/ai-vocabulary-builder#%E5%AF%BC%E5%87%BA%E7%94%9F%E8%AF%8D%E6%9C%AC

只是目前还不支持太多筛选参数。

**Comment by doublessay** [comment]
是的，我也看到了已有的这个导出功能，但是添加单词、学习单词是个比较动态的过程，并不想每当需要查看单词列表时，就导出一份csv。All in aivoc or terminal is great.

**Comment by piglei** [comment]
最新版本已经支持。

https://github.com/piglei/ai-vocabulary-builder#%E6%9F%A5%E7%9C%8B%E7%94%9F%E8%AF%8D
