### ISSUE TITLE
在interactive mode 添加remove 單詞功能

### ISSUE THREAD

**Issue by NateCC0902** [piglei/ai-vocabulary-builder#43]
如果誤添加某個單詞 

可以使用remove [voc] 移除 

或者 remove [num] 移除最近num個單詞

**Comment by piglei** [comment]
部分细节：

- 需要实现 Parser，避免和以 “remove” 打头的待翻译内容相冲突
- 需要基于 prompt-toolkit lib 实现自动补全生词，可以提升体验
- remove [num] 感觉不是特别有必要
- 目前移除实际上有两种做法：移入“已掌握单词”和完全删除，需要考虑实现哪一种

**Comment by NateCC0902** [comment]
考慮到未來要做quiz功能 已掌握可能被當作題庫 完全移除感覺會比較好點 例如 如果我不小心把太簡單的詞apple加入 我也自然不想quiz裡出現 太簡單的題

如果是已經掌握的單詞 可以在新贈mastered [vol]功能 ? 以及 mastered 進入選單查看最近單詞然後選擇？

**Comment by piglei** [comment]
已经在 0.5.0 版本中支持，可升级体验：

pip install --upgrade ai-vocabulary-builder
