### ISSUE TITLE
支持使用 no 命令一次选择包括原词在内的多个单词

### ISSUE THREAD

**Issue by piglei** [piglei/ai-vocabulary-builder#47]
当前：

- 用户输入 no 命令后，上一个被添加的生词会被丢弃（加入 known words）
- 列出 3 个可能的生词，用户可从中挑选 1 个

期望：

- 列出 3 个可能的生词，加上被丢弃的单词，共 4 个单词，用户可从中挑选多个

**Comment by piglei** [comment]
related: #24

**Comment by NateCC0902** [comment]
已放一個PR 但unit test等還沒寫和改 只是實現多選的基礎功能

**Comment by NateCC0902** [comment]
列出 3 个可能的生词，加上被丢弃的单词，共 4 个单词，用户可从中挑选多个

如果no 之後可以選原本的話 那就不需要丟棄單詞了 
get_mastered_word_store().add(word.word) 這段就可以刪掉了

**Comment by piglei** [comment]
已经在 0.5.0 版本中支持。
