### ISSUE TITLE
可以做成网页版的吗

### ISSUE THREAD

**Issue by wellbug** [piglei/ai-vocabulary-builder#50]
这个太好用了，如果可以做成html就完美了

**Comment by piglei** [comment]
一直在规划中，并且技术上完全可行。只是我业余时间有限，一直没有启动。我争取尽快吧。

**Comment by NateCC0902** [comment]
@piglei  想問一下作者打算用什麼框架 我有想試試看 ( code寫太爛就不pr了 🥲

**Comment by piglei** [comment]
> @piglei 想問一下作者打算用什麼框架 我有想試試看 ( code寫太爛就不pr了 🥲

争取最近一周内，找点时间先把原型画了。框架之后再定，前端我只对 Vue 熟（写过一点），后端估计会用 FastAPI。
