### ISSUE TITLE
能否增加命令行工具，便于跟其他软件集成

### ISSUE THREAD

**Issue by mobilestack** [piglei/ai-vocabulary-builder#51]
比如

`aivoc trans "sample text to be translated"`

这样可能便于跟类似Popclip这样的软件连接，也方便自动化程序调用。

可以考虑提供选项直接在stdout输出结果，或者提供识别结果的日志，此外，因为整个例句也都存入了，也相当于就是例句。唯一需要处理的是，自动化识别的唯一结果可能不是目标单词，也许可以加个行号或者其他index给这行，补充运行一下这一行就好。

**Comment by piglei** [comment]
提供独立的 trans 子命令方式是可行的。不过其实，你现在就可以用 `echo "this is a sentence" | aivoc run`[1] 来做到你说的事情。唯一的问题是输出不方便解析，如果想更方便一些，可以增加 JSON 格式的输出。

另外，在和 Popclip 等软件的集成方面，和调命令比起来，提供 #4 Server 模式走 REST API 可能会更好一些。因为很多插件实际上并不支持随意调本地命令，此外，“AI生词本”如果要开发自己的 Web UI，本身也是依赖 REST API 的。如果有了 Web UI，假如某次自动化识别不准确，用户可以通过访问 API 翻译的“修正”链接，打开独立的页面来手动选择单词，完成修正。

[1] 单次翻译

```
❯ echo "this is a sentence" | aivoc run
            翻译结果
┌──────────┬────────────────────┐
│ 原文     │ this is a sentence │
│ 中文翻译 │ 这是一个句子。     │
└──────────┴────────────────────┘


⠸  正在提取生词
> The word AI has chosen is "sentence".

┏━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━┓
┃ 单词     ┃ 发音        ┃ 释义 ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━┩
│ sentence │ ['ˈsɛntəns] │ 句子 │
└──────────┴─────────────┴──────┘
"sentence" was added to your vocabulary book (69 in total), well done!
```

**Comment by mobilestack** [comment]
好的，那就期待server模式的出现。

当下我包了一个命令来实现手头的诉求

```bash
#!/bin/bash

echo "$(pbpaste)" | aivoc run
```

虽然没有popclip一键点击那么快，不过也足够用
