### ISSUE TITLE
开发 Web 主界面：“提取生词”

### ISSUE THREAD

**Issue by piglei** [piglei/ai-vocabulary-builder#56]
低保真线框图：

![image](https://user-images.githubusercontent.com/731266/229331286-235de408-6837-4793-8bf5-85e096d52aca.png)

预期技术：

- Vue.js 实现前端
- FastAPI 实现后端 API
- 用户执行 `aivoc notebook` 启动本地服务器，自动打开浏览器进入首页

**Comment by mobilestack** [comment]
有了web界面后，备选生词可以考虑多选几个了。之前遇到一句话可能会有很多生词。而且很多情况下一般是选择一个段落去翻译的，生词就更不止一个了

**Comment by NateCC0902** [comment]
有進度了嗎

**Comment by piglei** [comment]
已经在 0.6.0 版本实现。
