### ISSUE TITLE
能否添加对于Deepseek的支持？

### ISSUE THREAD

**Issue by PipeYume** [piglei/ai-vocabulary-builder#72]
能否添加对于Deepseek的支持？Deepseek算是国内比较便宜又好用的高性价比AI了，支持OpenAI格式的接口。

**Comment by PipeYume** [comment]
试了下把模型、url、key换成Deepseek，会报错
```
voc_builder.exceptions.AIServiceError: Error calling AI backend API: Error code: 400 - {'error': {'message': "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. (insufficient tool messages following tool_calls message)", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_request_error'}}
INFO:     127.0.0.1:56670 - "POST /api/word_samples/extractions/ HTTP/1.1" 400 Bad Request
```

**Comment by piglei** [comment]
项目当前用到 [Pydantic AI]([Models - PydanticAI](https://ai.pydantic.dev/models/)) 对接不同的 LLM 服务商。看了下，Pydantic AI 项目目前不支持 DeepSeek，因此要做的话，得先用 Pydantic AI 的模式封装好 Deepseek 的 API 调用，然后生词本项目就可以直接启用 DeepSeek 了。

目前我暂时没有精力处理这部分对接工作，会先等待看看。

**Comment by HaveF** [comment]
https://api-docs.deepseek.com/zh-cn/

deepseek 和 openai 接口是兼容的吧? 现在界面中能够设置 base url 和 key, 我怀疑是不是选openai, 然后在设置模型的地方能够允许自定义输入模型名(而非只能下拉框)就可以了?

**Comment by PipeYume** [comment]
> https://api-docs.deepseek.com/zh-cn/
> 
> deepseek 和 openai 接口是兼容的吧? 现在界面中能够设置 base url 和 key, 我怀疑是不是选openai, 然后在设置模型的地方能够允许自定义输入模型名(而非只能下拉框)就可以了?

我直接改的config文件让模型名变成了deepseek的。然后有上述报错。

**Comment by piglei** [comment]
@PipeYume 报错的原因是 DeepSeek 不完全兼容 OpenAI API 的 function call。

--

翻了会文档，我基于 DeepSeek 的 JSON OUTPUT 实现了功能，已经在 1.3.0 版本发布，欢迎使用，欢迎反馈。 @HaveF  @PipeYume 

https://pypi.org/project/ai-vocabulary-builder/1.3.0/

**Comment by HaveF** [comment]
@piglei amazing! 感谢! 一会试试

**Comment by HaveF** [comment]
Hi, @piglei 尝试了下，简单说下体验:

1. 基础感觉打的很好，看得出是花了不少心思和时间的 👍 
2. 有一些不一样的视角(大概率不对)，简单说下。
   - `ai-vocabulary-builder` 是为谁 builder? 是为后面的选择题 build 吗? 后面的选择题类型的记忆方式显然要比现在的一些记忆工具(anki, supermemo)功能上简单很多, 如果再考虑艾宾浩斯遗忘曲线，那么整体复杂度会上升很多。
   - 单句抽取单词用起来感觉有点麻烦，如果用户直接复制一篇 markdown 或任何文字档的东西，一次提取出来比如说20个(用户根据自己情况自定义?), 然后将 20 个同时生成含义和例句, 用户在学完之后，再去阅读原文效果不是更好? JSON output 一次输出应该也没太大问题。
   - 用户的使用场景究竟是什么呢? 还是只是把原来查字典的工作往前推进了一步?

刚好昨天在 HN 上看到一篇相关的，供参考: [Show HN: Anki AI Utils | Hacker News](https://news.ycombinator.com/item?id=42534931)

**Comment by piglei** [comment]
@HaveF 这个工具最适合的使用场景，是在英文阅读过程中采集生词。

长期以来，我的英文词汇量处在一个比较尴尬的位置。说小不小，能流畅阅读大部分英文文章、书籍，全文翻译软件对我来说是一种干扰。但要说词汇量大，其实又不够大，时常会遇到几个生词，有时懒得查词就混过去，或查一下释义，但过了一两个月再次遇到发现还是不认识。

所以，我开发了这个工具，满足在英文阅读时快速采集生词的需求。因为开发时间有限，之前主要放在了“词汇采集“上，像你提到的，在后续的“助记“实际做的很初级。如果继续完善，是可以增加 Anki 卡片集成、遗忘曲线等功能，都是很好的巩固方式。后续，我会继续改进（下一步准备先实现单个单词的采集功能）。

**Comment by HaveF** [comment]
@piglei 啊哈，你这么说我就明白了。

如果能把单词和句子的采集功能做到极致，我觉得就非常非常好了。

单个单词的采集功能不是完成了吗? https://github.com/piglei/ai-vocabulary-builder/blob/main/docs/integrations.md#popclip

只需要判断采集的 text 有没有空格是不是就可以了?

另外，因为主要阅读的都是网页，相比于 popclip，我觉得 tampermonkey 采集可能更简单且跨平台

另外，我想能不能直接增加一个复制的功能(现在有的功能是导出)，比如复制出一定的单词和对应的句子，再加上默认的 prompt，直接粘贴到任何的聊天工具中，就可以直接进行巩固学习了。

```
请帮我根据如下的单词和例句，拆解单词词根，帮我辅助记忆，甚至帮我绘制出可能有助于我记忆的图片帮我理解记忆，最后生成一个300字的短文帮我综合这些单词辅助我练习。单词和例句如下:

单词@例句
xxx@zzzzz zzzz zzzz
ggg@aaa aaa aaa
...
...
...

```

**Comment by piglei** [comment]
关于采集单个单词，因为目前软件限制了输入不少于 12 个字符，所以一个词无法通过校验。我准备调整为，当用户只输入了一个单词时，调用 AI 生成几个助记的例句，之后的采集流程和输入整句相同。

---

关于你提到的拆解词根、绘图助记等功能，都是非常有意思的点，而且通过 LLM 的能力，实际上不用花费多大的气力就能实现。这也是我觉得开发这个小工具最有意思的部分：只要我们能想到的可借助 LLM 拓展词汇量的电子，都可以编码实现。😁
