### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 14: character maps to <undefined>

### ISSUE THREAD

**Issue by Fit-yourself** [piglei/ai-vocabulary-builder#9]
## 問題

- 在終端中，輸入`aivoc`，界面正常：
![无标题](https://user-images.githubusercontent.com/45476879/223047637-8f33b812-c944-4ce8-815c-076746be7037.png)

- 黨輸入内容后，出現錯誤：
![无标题2](https://user-images.githubusercontent.com/45476879/223047742-9d6ac452-9763-450f-98a4-2e920a9a2c4e.png)

---
OpenAI_key 也是正確的

## 系統信息

 - Windows 11 22621
 - Python  3.10.8

---
請問，是我環境哪個部分哪裏出問題了嗎？

**Comment by piglei** [comment]
你好，是之前能用，更新后不可用吗？怀疑可能是新版本修改了默认编码所导致。

- 试着删除一下截图中的 csv 生词本文件（或者将它挪到别的位置）
- 使用 `aivoc --log-level DEBUG` 启动后，正常测试使用
- 如果有报错，把详细的报错信息贴到这里来

**Comment by piglei** [comment]
请试着更新到最新版 0.1.2，我试着修复了这个问题：

    pip install --upgrade ai-vocabulary-builder
